--      CODER ABHIX         SQL          -14-06-2020-
CREATE TABLE STUDENT1(ST_ROLL NUMBER(6), ST_NAME VARCHAR2(30), ST_ADDR VARCHAR2(50), PRIMARY KEY (ST_ROLL));

CREATE TABLE SUBJECT (SUB_ID VARCHAR2(6), T_NAME VARCHAR2(30), PRIMARY KEY (SUB_ID));

CREATE TABLE TEACHER (T_NAME VARCHAR2(30), T_ADDR VARCHAR2(50), T_DESIG VARCHAR2(12), PRIMARY KEY (T_NAME));

CREATE TABLE CLASS (CL_R_NO  NUMBER(4), YEAR VARCHAR2(8), SUB_ID VARCHAR2(6), PRIMARY KEY (CL_R_NO));

CREATE TABLE MARKS (SUB_ID VARCHAR2(6), ST_ROLL NUMBER(6), MARKS NUMBER(3));
-- a) List the marks obtained by a student for a given st_roll.
SELECT MARKS FROM MARKS WHERE ST_ROLL =1 ;

-- b) Find the total marks obtained by a student.
SELECT SUM(MARKS) AS TOTAL_MARKS FROM MARKS WHERE ST_ROLL=1 GROUP BY (ST_ROLL);

-- c) Find the percentage of marks obtained by a student.
SELECT SUM(MARKS)/COUNT(MARKS) AS MARKS_PERCENTAGE FROM MARKS WHERE ST_ROLL=1 GROUP BY (ST_ROLL);

-- d) List the names of teacher in sorted order.
SELECT T_NAME FROM TEACHER ORDER BY T_NAME ASC;

-- e) Find the class-room-id foe subjects in sorted order subject wise.
SELECT C.CL_R_NO FROM CLASS C INNER JOIN SUBJECT S ON C.SUB_ID = S.SUB_ID WHERE S.T_NAME='AAA';

-- f) List the names of students in sorted order subject wise.
SELECT  S.ST_NAME,  M.SUB_ID FROM STUDENT1 S INNER JOIN MARKS M ON S.ST_ROLL = M.ST_ROLL GROUP BY (M.SUB_ID, S.ST_NAME) ORDER BY (S.ST_NAME) ASC;

-- g) List the names of student who got maximum marks subject wise.

SELECT S.ST_NAME, M.MARKS FROM STUDENT1 S INNER JOIN  MARKS M ON S.ST_ROLL = M.ST_ROLL WHERE (M.MARKS,M.SUB_ID) IN (
SELECT MAX(MARKS.MARKS), SUB_ID FROM MARKS
GROUP BY (MARKS.SUB_ID) );

-- h) Find the name of subject who got maximum total marks.

SELECT ST_NAME, MAXSUM AS MAXIMUM_MARKS FROM
(SELECT ST_NAME, SUM(M.MARKS) MAXSUM FROM STUDENT1 S INNER JOIN  MARKS M ON S.ST_ROLL = M.ST_ROLL GROUP BY S.ST_ROLL,S.ST_NAME) s1
WHERE s1.MAXSUM = (
SELECT MAX(SUM(MARKS)) FROM MARKS GROUP BY (ST_ROLL) ) ;

SELECT * FROM STUDENT1;
SELECT * FROM MARKS;
TRUNCATE TABLE MARKS;
INSERT INTO STUDENT1 VALUES (1, 'AAA', 'KOLKATA');
INSERT INTO STUDENT1 VALUES (2, 'BBB', 'DGP');
INSERT INTO MARKS VALUES (11,1,100);
INSERT INTO MARKS VALUES (12,1,90);
INSERT INTO MARKS VALUES (11,2,90);
INSERT INTO MARKS VALUES (12,2,70);

